---
- name: Install MongoDB
  apt:
    name: mongodb
    state: present
    update_cache: yes

- name: Ensure MongoDB is running
  service:
    name: mongodb
    state: started
    enabled: yes

- name: Allow external connections to MongoDB
  lineinfile:
    path: /etc/mongodb.conf
    regexp: '^bind_ip'
    line: 'bind_ip = 0.0.0.0'
  notify: Restart MongoDB

- name: Open MongoDB port
  ufw:
    rule: allow
    port: 27017
    proto: tcp

- name: Restart MongoDB
  service:
    name: mongodb
    state: restarted
